export const metaDataOptions = [
  ['-T, --test', 'test if file is mp4'],
  ['-p, --textdata', 'print the metadata tags'],
  ['-a, --artist <artist>', 'set the artist of the file'],
  ['-t, --title <title>', 'set the title of the file'],
  ['-g, --genre <genre>', 'set the genre of the file'],
  ['-n, --tracknum <tracknum>', 'set the track number of the file'],
  ['-c, --comment <comment>', 'set the comment for the file'],
  ['-y, --year <year>', 'set the year of the file'],
  ['-c, --composer <composer>', 'set the composer of the file'],
  ['-r, --copyright <copyright>', 'set the copyright of the file'],
  ['-i, --artwork <artwork>', 'set the artwork of the file'],
  ['-s, --albumArtist <artist>', 'set the artist of the file'],
  ['-d, --description <description>', 'set the description of the file'],
]